param(
    [Parameter(Mandatory = $true)][string]$Version,
    [Parameter(Mandatory = $true)][string]$Tag,
    [Parameter(Mandatory = $true)][string]$Repository,
    [Parameter(Mandatory = $true)][string]$InputRoot,
    [Parameter(Mandatory = $true)][string]$OutputDirectory
)

$ErrorActionPreference = "Stop"
if ($Version -notmatch '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$' -or $Tag -ne "v$Version") {
    throw "Manifest version/tag identity is invalid: version=$Version tag=$Tag"
}
$root = (Resolve-Path -LiteralPath $InputRoot).Path
New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null
$output = [IO.Path]::GetFullPath($OutputDirectory)

function Find-One([string]$name) {
    $matches = @(Get-ChildItem -LiteralPath $root -Recurse -File | Where-Object Name -eq $name)
    if ($matches.Count -ne 1) { throw "Expected exactly one $name below $root, found $($matches.Count)." }
    return $matches[0]
}

function Verify-Sidecar([IO.FileInfo]$artifact) {
    $sidecar = Find-One ($artifact.Name + '.sha256')
    $expected = ((Get-Content -LiteralPath $sidecar.FullName -Raw) -split '\s+')[0].Trim().ToLowerInvariant()
    $actual = (Get-FileHash -LiteralPath $artifact.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($expected -notmatch '^[0-9a-f]{64}$' -or $expected -ne $actual) {
        throw "Checksum mismatch for $($artifact.Name)."
    }
    return [ordered]@{ sha256 = $actual; bytes = $artifact.Length; sidecar = $sidecar }
}

function Verify-ComponentManifest([string]$name, [string]$role) {
    $file = Find-One $name
    $json = Get-Content -LiteralPath $file.FullName -Raw | ConvertFrom-Json
    if ($json.schemaVersion -ne 1 -or $json.componentRole -ne $role -or $json.version -ne $Version -and $json.releaseVersion -ne $Version) {
        throw "Component manifest identity mismatch in $name."
    }
    return $file
}

$windowsName = "LokiTrafficLab-windows-x64-$Version.zip"
$linuxName = "LokiTrafficLab-linux-x64-$Version.tar.gz"
$androidName = "LokiTrafficLab-android-$Version.apk"
$windows = Find-One $windowsName
$linux = Find-One $linuxName
$android = Find-One $androidName
$bootstrap = Find-One 'bootstrap.sh'
$windowsDigest = Verify-Sidecar $windows
$linuxDigest = Verify-Sidecar $linux
$androidDigest = Verify-Sidecar $android
$bootstrapDigest = Verify-Sidecar $bootstrap
$windowsManifest = Verify-ComponentManifest 'windows-manifest.json' 'traffic-lab-windows-portable-client'
$linuxManifest = Verify-ComponentManifest 'linux-manifest.json' 'traffic-lab-linux-client'
$androidManifest = Verify-ComponentManifest 'android-manifest.json' 'traffic-lab-android-client'

$baseUrl = "https://github.com/$Repository/releases/download/$Tag"
$artifacts = @(
    [ordered]@{ platform = 'windows'; architecture = 'x64'; kind = 'portable-zip'; file = $windows.Name; url = "$baseUrl/$($windows.Name)"; bytes = $windowsDigest.bytes; sha256 = $windowsDigest.sha256; componentManifest = $windowsManifest.Name },
    [ordered]@{ platform = 'linux'; architecture = 'x64'; kind = 'self-contained-install-archive'; file = $linux.Name; url = "$baseUrl/$($linux.Name)"; bytes = $linuxDigest.bytes; sha256 = $linuxDigest.sha256; componentManifest = $linuxManifest.Name; bootstrap = $bootstrap.Name },
    [ordered]@{ platform = 'android'; architecture = 'arm64-v8a,x86_64'; kind = 'apk'; file = $android.Name; url = "$baseUrl/$($android.Name)"; bytes = $androidDigest.bytes; sha256 = $androidDigest.sha256; componentManifest = $androidManifest.Name }
)
$linuxInstall = "curl -fsSL $baseUrl/bootstrap.sh -o /tmp/tlab-bootstrap.sh && echo '$($bootstrapDigest.sha256)  /tmp/tlab-bootstrap.sh' | sha256sum -c - && sudo bash /tmp/tlab-bootstrap.sh --url $baseUrl/$linuxName"
$manifest = [ordered]@{
    schemaVersion = 1
    componentRole = 'traffic-lab-multi-platform-release'
    version = $Version
    tag = $Tag
    channel = 'stable'
    source = [ordered]@{ repository = $Repository; commit = $env:GITHUB_SHA }
    compatibility = [ordered]@{ windows = 'Windows 10/11 x64'; linux = 'Ubuntu 22.04/24.04 x64'; android = 'Android API 26+; arm64-v8a or x86_64' }
    artifacts = $artifacts
    installation = [ordered]@{ linuxOneCommand = $linuxInstall }
    trust = [ordered]@{
        sha256 = 'Binds downloaded bytes to this manifest; a checksum is not a publisher signature.'
        githubArtifactAttestation = 'Generated by the tag-triggered GitHub Actions release workflow for published files.'
        androidPackageSignature = 'Build-environment debug identity; suitable for direct testing, not store publication or stable-key upgrades.'
        bootstrapBoundary = 'The command verifies bootstrap.sh against this manifest value. Trust in the initial manifest/release page still depends on GitHub HTTPS and repository controls.'
    }
}
$manifestPath = Join-Path $output 'release-manifest.json'
$manifest | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath $manifestPath -Encoding utf8
$manifestHash = (Get-FileHash -LiteralPath $manifestPath -Algorithm SHA256).Hash.ToLowerInvariant()
"$manifestHash  release-manifest.json" | Set-Content -LiteralPath "$manifestPath.sha256" -Encoding ascii
$installText = @"
Loki Traffic Lab $Version - Linux one-command installation

$linuxInstall

The command verifies bootstrap.sh against the release contract. bootstrap.sh
then downloads both the Linux archive and its SHA-256 sidecar and refuses a
mismatch before extraction. See release-manifest.json for trust boundaries.
"@
$installText | Set-Content -LiteralPath (Join-Path $output 'INSTALL-LINUX.txt') -Encoding utf8

$releaseFiles = @($windows, $windowsDigest.sidecar, $linux, $linuxDigest.sidecar, $android, $androidDigest.sidecar, $bootstrap, $bootstrapDigest.sidecar, $windowsManifest, $linuxManifest, $androidManifest)
foreach ($file in $releaseFiles) { Copy-Item -LiteralPath $file.FullName -Destination (Join-Path $output $file.Name) -Force }
$sumLines = Get-ChildItem -LiteralPath $output -File | Where-Object { $_.Name -notin @('SHA256SUMS', 'release-manifest.json.sha256') } | Sort-Object Name | ForEach-Object {
    "{0}  {1}" -f (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant(), $_.Name
}
$sumLines | Set-Content -LiteralPath (Join-Path $output 'SHA256SUMS') -Encoding ascii
Write-Host "Release manifest and $($releaseFiles.Count + 4) publication files prepared in $output"
